# to display an unique number 
s = set()
n = int(input("Enter a number: "))
s.add(int(n))
n = int(input("Enter a number: "))
s.add(int(n))
n = int(input("Enter a number: "))
s.add(int(n))
n = int(input("Enter a number: "))
s.add(int(n))
n = int(input("Enter a number: "))
s.add(int(n))
n = int(input("Enter a number: "))
s.add(int(n))
n = int(input("Enter a number: "))
s.add(int(n))
n = int(input("Enter a number: "))
s.add(int(n))
print(s)
