# Generated by Django 4.0.3 on 2025-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('fee', models.FloatField()),
            ],
        ),
    ]
