# 1.Write a program to find length of
# number (count of digits)
# n=int(input("Enter a number:"))


# a=float(input("Entera  nuber :"))
# b=float(input("Entera  nuber :"))
# if(a>b):
#     print(f"A is bigger{a}")
# else:
#     if(a<b):
#         print(f"B is bigger {b}")
#     elif(a==b):
#         print("both are same")
#     else:
#         print("it is Zero")            



# s="python"
# print("p" in s)
# print("p"not in s)
# print("k" in s)
# print("k"  not in s)


# print(10 is 20)
# x=10
# y=10
# # print(x is y)
# print(x,id(x))
# print(y,id(y))

# a=12
# b=13
# print(a,id(a))
# print(b,id(b))
# print(a is b)

# d1={10:"mango",20:"apple",30:"gava"}
# d2={10:"mango",20:"apple",30:"gava"}
# print(d1,id(d1))
# print(d2,id(d2))
# print(d1 is d2)
# print(d1  is not d2)

# s1={10,20,30,40,1}
# s2={10,20,30,40,1}
# print(s1,id(s1))
# print(s2,id(s2))
# print(s1 is s2)

# t1=(10,20,30)
# t2=(10,20,30)
# print(t1 is t2)

# >>> t1=(10,20,70,80)
# >>> t2=(10,20,70,80)
# >>> print(t1,type(t1),id(t1))
# (10, 20, 70, 80) <class 'tuple'> 1976733650272
# >>> print(t2,type(t2),id(t2))
# (10, 20, 70, 80) <class 'tuple'> 1976733651072
# t1 is t2
# # False
# t1 is not t2
# # True
# t1=(10,20,70,80)
# t2=(10,20,70,80)
# print(t1 ,id(t1))
# print(t2 ,id(t2))
# print(t1 is t2)
# print(t1 is not t2)

# r1=range(10,20,2)
# r2=range(10,20,2)
# print(r1,id(r1))
# print(r2,id(r2))
# print(r1 is r2)

# a=10
# b=10
# print(a,id(a))
# print(b,id(b))
# print(a is b)

# a=1.2
# b=1.2
# print(a,id(a))
# print(b,id(b))
# print(a is b)

# a=2+3j
# b=2+3j
# print(a,id(a))
# print(b,id(b))
# print(a is b)

# a=399
# b=399
# print(a,id(a))
# print(b,id(b))


# a=5
# b=5
# print(a,id(a))
# print(b,id(b))

# value=input("Entera  value:")
# # if(value==list(value).reverse()):
# if(value==value[::-1]):
#     print("Palindrome value")
# else:
#     print("it is not palindeome")    

# =====================================================================================
# SUNDAY PRACTICE
# =====================================================================================
#strating a while loop 1 2 3 4 5 6 
# i=int(input("Enter a number  FOR STARTING A LOOP:"))
# n=int(input("Enter anumber for ENDING THE LOOP :"))
# while(i<=n):
#     print(i)
#     i=i+1


#Strating the loop for loop 1 2 3 4 5 
# i=int(input("Enter a number  FOR STARTING A LOOP:"))
# n=int(input("Enter anumber for ENDING THE LOOP :"))
# for i in range(i,n+1):
#     print(i)


# while loop in reversed order in while loop
# i=int(input("Enter a number  FOR STARTING A LOOP:")) #10
# n=int(input("Enter anumber for ENDING THE LOOP :"))   #1
# while(i>=n):
#     print(i)
#     i=i-1



#  while loop in reversed order in while loop
# i=int(input("Enter a number  FOR STARTING A LOOP:")) #10
# n=int(input("Enter anumber for ENDING THE LOOP :"))   #1
# for i in range(i,n-1,-1):
#     print(i)

#even number with the help of while loop
# i=int(input("Enter a number  FOR STARTING A LOOP:")) #10
# n=int(input("Enter anumber for ENDING THE LOOP :"))   #1
# while(i<=n):
#     print(i)
#     i=i+2


# # even number with the help of while loop
# i=0 #=int(input("Enter a number  FOR STARTING A LOOP:")) #10
# n=int(input("Enter anumber for ENDING THE LOOP :"))   #1
# for i in range(i,n+1,2):
#     print(i)


 # even number with the help of while loop
# i=0 #=int(input("Enter a number  FOR STARTING A LOOP:")) #10
# n=int(input("Enter anumber for ENDING THE LOOP :"))   #1
# while(i<=n):
#     print(i)
#     i=i+2


# odd number with the help of while loop
# sum=0
# i=1 #=int(input("Enter a number  FOR STARTING A LOOP:")) #10
# n=int(input("Enter anumber for ENDING THE LOOP :"))   #1
# while(i<=n):
#     print(i)
#     sum=sum+i
#     i+=2
# print("sum of odd",sum)    


# odd number with the help of while loop
# sum=0
# i=1 #=int(input("Enter a number  FOR STARTING A LOOP:")) #10
# n=int(input("Enter anumber for ENDING THE LOOP :"))   #1
# for i in range(i,n+1,2):
#     print(i)
#     sum=sum+i
# print("sum of odd",sum)    

# sum=0
# for i in range(5,51,5):
#     print(i)
#     if(i%2!=0):
#         sum=sum+i

# print( "sum =>",sum)        

# Write a program to find max of two integers
# n=int(input("Enter a number :"))
# m=int(input("Enter a number :"))
# if(n>m):
#     print(f"the bigest value is {n}")
# if(n<m):
#     print(f"the bigest value is {m}")
# if(n==m):
#     print(f"Both value is biggest ")
# Example:

# Walres operator in python

# a=10
# b=20
# avg=(tot:=a+b)/2
# print(a,b,tot,avg,sep="\n")
# Output
# 10
# 20
# 30
# 15.0



# a=10
# b=20
# avg=0
# print((a+b)//2)
# print(30//2)


# Write a program to find a person is elg to vote or not
# num=int(input("Enter a  number :"))
# age=int(input("Entera  number :"))
# if(age<=0):
#     print("please enter valid age")
# elif(age<18 and age>100):
#     print("person is not eligible for vote")
# elif(age>18):
#     print("person is  eligible for vote")      
# elif(age>=100):
#     print("WHY ARE YOU COME TO VOTE")    

# Write a program to find input number is even or odd
# num=int(input("Enter a number :"))
# if(num%2==0):
#     print("EVEN NUMBER",num)
# else:
#     print("ODD NUMBER",num)    

# Write a program to check a number is divisible with 7 or not
# num=int(input("Enter a number :"))
# if(num%7==0):
#     print("divisible by 7")
# else:
#     print(" it is not divisible by 7")  



# Write a program to print "Hello" if number
# is multiples of 5 otherwise print  " Bye "
# num=int(input("Enter a number :"))
# if(num%5==0):
#     print("numtiple  by 5")
# else:
#      print(" it is not numtiple  by 5") 


# =========================================
# for loop
# =========================================
# n= int(input("Entera  number  first number:"))
# m= int(input("Entera  number last number :"))
# for i in range(n,m,1):
#     print(i)



# m= int(input("Entera  number last number :"))
# n= int(input("Entera  number  first number:"))
# for i in range(m,n,-1):
#     print(i)

# i= int(input("Entera  number  first number:"))
# n= int(input("Entera  number last number :"))
# while(i<n):
#     print(i)
#     i=i+1

# i= int(input("Entera  number  first number:"))
# # m= int(input("Entera  number  first number:"))
# while(i>=0):
#     print(i)
#     i=i-1

# n=int(input("Entera number :"))
# i=1
# s=0
# while(i<=10):
#     print( f" {n}  X  {i}  = {n*i}")
#     if(i%2==0):
#         s=s+i*n
#     i=i+1
# print(s)    


# n=int(input("Entera number :"))
# s=0
# for i in range(1,11):
#     print(f" {n*i}")
#     if(i%2==0):
#         s=s+i*n
# print( "sum of even number in table :",s)        


# n=int(input("Entera  number :"))
# s=0
# sqsum=0
# cubes=0
# i=1
# while(i<=n):
#     print(f" {i}   {i*i}   {i**3}")
#     s=s+i
#     sqsum=sqsum + i*i
#     cubes=cubes+i**3
#     i=i+1
# print(f"sum => ",s)    
# print(f"square of sum=>",sqsum)
# print("cube of sum =>",cubes)


# n=int(input("Enter a number :"))
# s=0
# ss=0
# cs=0
# i=1
# while(i<=n):
#     print(f" {i}  {i**2}  {i**3}")
#     s=s+i
#     ss=ss+i**2
#     cs=cs+i**3
#     i=i+1
# else:
#     print("------------------")
#     print(f"{s}  {ss}   {cs}")


# n=int(input("Entera  number :"))
# if(n%2==0):
#     print("it is even number :")
# if(n%2!=0):
#     print("it is odd number")    
# print("program Execution Completed :")


# n=int(input("Entera  number :"))
# if(n>0):
#     print("POSITIVE")
# if(n<0):
#     print("NEGATIVE")    





