# Generated by Django 4.0.3 on 2025-11-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=25)),
                ('job', models.CharField(max_length=15)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
