# Generated by Django 4.0.3 on 2025-11-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empmodel',
            table='emp',
        ),
    ]
