# Generated by Django 4.0.3 on 2025-11-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_empmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmodel',
            old_name='salary',
            new_name='sal',
        ),
    ]
