# Generated by Django 4.0.3 on 2025-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('Empno', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=25)),
                ('job', models.CharField(max_length=15)),
                ('sal', models.FloatField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
