from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def calculator(request):
    num1 = eval(request.GET.get("n1"))
    num2 = eval(request.GET.get("n2"))
    cmd = request.GET.get("b1")
    match(cmd):
        case "Add":
            num3 = num1+num2
        case "Sub":
            num3 = num1-num2
        case "Mul":
            num3 = num1*num2
        case "Div":
            num3 = num1/num2
    #* output is generated by views
    output = f'<center><h2>Result is {num3}</h2></center>'   
    response = HttpResponse(output)  
    #* output is generated by templates urls.py madhe taka lagte fakta 
    # response = render(request,"result.html")
    return response 
#! Ha function display karate na templates sathi aahe 
def index(request):
    response = render(request,"calc.html",context={})
    return response