# Generated by Django 4.0.3 on 2025-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='eligibility',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
